#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: dockerhost
#  labels:
#    k8s-app: dockerhost
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      k8s-app: dockerhost
#  template:
#    metadata:
#      labels:
#        k8s-app: dockerhost
#    spec:
#      containers:
#      - name: dockerhost
#        image: qoomon/docker-host
#        securityContext:
#          capabilities:
#            add: ["NET_ADMIN", "NET_RAW"]
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: dockerhost
#spec:
#  clusterIP: None # <-- Headless service
#  selector:
#    k8s-app: dockerhost
---
apiVersion: v1
kind: Service
metadata:
  name: dockerhost
spec:
  type: ExternalName
  externalName: host.docker.internal
